services:
  api:  
    build: 
      context: .
      dockerfile: ./api/Dockerfile
    # env_file: 
    #   - ${ENV_FILE_PATH:-config.env}
    ports: 
      - 8080:80
    restart: always
    volumes:
      - ./api/app:/app
  
  machine_learn:
    build: 
      context: .
      dockerfile: ./machine_learn/Dockerfile
    ports: 
      - 8888:8888
    volumes:
      - ./machine_learn:/machine_learn