services:
  api:  
    build: 
      context: .
      dockerfile: ./api.Dockerfile
    # env_file: 
    #   - ${ENV_FILE_PATH:-config.env}
    ports: 
      - 8080:80
    restart: always
    volumes:
      - ./api/app:/app
      - ./face_ee_manager:/app/face_ee_manager
  
  machine_learn:
    build: 
      context: .
      dockerfile: ./machine_learn/Dockerfile
    ports: 
      - 8888:8888
    volumes:
      - ./machine_learn:/app
  
  recognition_api:
    build: 
      context: .
      dockerfile: ./recognition_api/Dockerfile
    ports: 8000:80
    restart: always
    volumes: ./recognition_api:/app

