services:
  api:  
    build: 
      context: .
      dockerfile: ./api.Dockerfile
    env_file: 
      - ${ENV_FILE_PATH:-api/.env}
    ports: 
      - 8080:80
    restart: always
    volumes:
      - ./api/app:/app
      - ./face_ee_manager:/face_ee_manager
  
  db:
    image: mariadb:latest
    env_file: 
      - ${ENV_FILE_PATH:-api/.env}
    ports:
      - 3306:3306
    # volumes: 
    # - ./db/data:/var/lib/mysql

  machine_learn:
    build: 
      context: .
      dockerfile: ./machine_learn/Dockerfile
    ports: 
      - 8888:8888
    volumes:
      - ./machine_learn:/app
