import os

PROJECT_NAME = os.getenv("PROJECT_NAME")
API_ROOT_PATH = os.getenv("API_ROOT_PATH")

# DB関連
MARIADB_SERVER = os.getenv("MARIADB_SERVER")
MARIADB_DATABASE = os.getenv("MARIADB_DATABASE")

MARIADB_USER = os.getenv("MARIADB_USER")
MARIADB_PASSWORD = os.getenv("MARIADB_PASSWORD")

SQLALCHEMY_DATABASE_URI = (
    f"mysql+pymysql://{MARIADB_USER}:{MARIADB_PASSWORD}@{MARIADB_SERVER}/{MARIADB_DATABASE}"
)

NOTIFY = os.getenv("NOTIFY")
